
enum Types {
    UPDATE_DESCRIPTION = 'UPDATE_DESCRIPTION',
    UPDATE_MIN_VALUE = 'UPDATE_MIN_VALUE',
    UPDATE_MAX_VALUE = 'UPDATE_MAX_VALUE',
    UPDATE_MAX_DISPLAY_VALUE = 'UPDATE_MAX_DISPLAY_VALUE'
}

export default Types;
