
enum Types {
    CREATE_COUNTER = 'CREATE_COUNTER',
    DELETE_COUNTER = 'DELETE_COUNTER',
    INCREMENT_COUNTER = 'INCREMENT_COUNTER',
    DECREMENT_COUNTER = 'DECREMENT_COUNTER'
}

export default Types;